name = "Upcontent"
license = "MIT"
licenselink = "https://github.com/.../.../LICENSE.md"
description = ""
homepage = "http://upcontent.com/"
tags = ["", ""]
features = ["", ""]

[author]
  name = "Kyle Grady"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
